-- DEV ONLY — replay a real recorded game onto Medville / Bogwater.
-- Do NOT run on PROD.
--
-- Source: recorded data/bengals-shots-vs-olympus-2026-08-19.csv
-- Generated by scripts/generate_dev_recorded_game_sql.py — re-run after CSV or mapping edits.
-- Attaches to DEV Sandbox playoffs on 2099-04-05 (Bogwater home, Medville away).
-- Safe to re-run: replaces shots on that game only.
--
-- Brighton → Medville
--   # 5 → #5   RB   Kate → Biscuit
--   # 8 → #9   RW   Addison → Pip
--   # 9 → #11  LW   Georgia → Pixel
--   #13 → #14  CF   Kailee → Pretzel
--   #17 → #6   LM   Jackie → Cosmo
--   #24 → #7   DM   Savvy → Nimbus
--   #26 → #8   RM   Sharky → Ziggy
--   #32 → #10  CF   Ari → Nova
--
-- Olympus → Bogwater
--   #10 → #10  DM   Olympus #10 → Reed
--   #14 → #14  RM   Olympus #14 → Moss
--   #15 → #9   CF   Olympus #15 → Bracken
--   #21 → #21  CF   Olympus #21 → Newt
--   #24 → #8   LM   Olympus #24 → Fen
--   #29 → #11  LW   Olympus #29 → Toad
--   #37 → #7   RW   Olympus #37 → Marsh
--   #55 → #6   LCB  Olympus #55 → Peat
--   #97 → #16  DM   Olympus #97 → Duckweed

do $$
declare
  marauders uuid;
  season uuid;
  opp uuid;
  gid uuid;
  tid uuid;
  pid uuid;
  apid uuid;
  jersey text;
  ajersey text;
begin
  select id into marauders from public.teams where is_brighton limit 1;
  select id into season from public.seasons where label = 'DEV Sandbox' limit 1;
  select id into opp from public.teams where name = 'Bogwater Badgers' limit 1;
  if marauders is null or season is null or opp is null then
    raise exception 'Run supabase/seed_dev_sandbox.sql on DEV first';
  end if;

  select g.id into gid from public.games g
  where g.season_id = season and g.date = '2099-04-05'
    and g.home_team_id = opp and g.away_team_id = marauders
  limit 1;
  if gid is null then
    insert into public.games (
      season_id, date, game_type, home_team_id, away_team_id, our_team_id,
      clock_direction, clock_half_length_sec, clock_et_length_sec
    ) values (
      season, '2099-04-05', 'playoffs', opp, marauders, marauders,
      'down', 2400, 600
    ) returning id into gid;
  else
    update public.games
    set clock_direction = 'down',
        clock_half_length_sec = 2400,
        clock_et_length_sec = 600
    where id = gid;
  end if;

  delete from public.shots where game_id = gid;

  -- 30 shots, oldest first

    -- 1 Bogwater #7 Shot on Goal  (Olympus #37 → Marsh)
    tid := opp;
    jersey := '7';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '1', tid, pid, jersey, 'RW',
      44.8, 20.6, 'RHS-D', 'Right half-space · Top of the box', 'on-target',
      apid, null, null,
      null, null, null, null,
      180, '2099-04-06T01:50:05.770Z'::timestamptz
    );

    -- 1 Medville #6 Missed Shot  (Jackie → Cosmo)
    tid := marauders;
    jersey := '6';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Medville jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '1', tid, pid, jersey, 'LM',
      41.4, 24.5, 'C-D', 'Zone 14', 'missed',
      apid, null, null,
      null, null, null, null,
      246, '2099-04-06T01:51:15.143Z'::timestamptz
    );

    -- 1 Bogwater #9 Missed Shot  (Olympus #15 → Bracken)
    tid := opp;
    jersey := '9';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '1', tid, pid, jersey, 'CF',
      34, 36, 'C-HALF', 'Center · Toward halfway', 'missed',
      apid, null, null,
      null, null, null, null,
      358, '2099-04-06T01:53:12.805Z'::timestamptz
    );

    -- 1 Bogwater #14 Missed Shot  (Olympus #14 → Moss)
    tid := opp;
    jersey := '14';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '1', tid, pid, jersey, 'RM',
      44.7, 16.6, 'RHS-D', 'Right half-space · Top of the box', 'missed',
      apid, null, null,
      null, null, null, null,
      442, '2099-04-06T01:54:40.797Z'::timestamptz
    );

    -- 1 Medville #11 Missed Shot  (Georgia → Pixel)
    tid := marauders;
    jersey := '11';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Medville jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '1', tid, pid, jersey, 'LW',
      52.7, 24.5, 'RHS-D', 'Right half-space · Top of the box', 'missed',
      apid, null, null,
      null, null, null, null,
      874, '2099-04-06T02:02:13.262Z'::timestamptz
    );

    -- 1 Medville #9 Goal  (Addison → Pip)
    tid := marauders;
    jersey := '9';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Medville jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    ajersey := '5';
    select r.player_id into apid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = ajersey
    limit 1;
    if apid is null then
      raise exception 'Medville assist jersey % missing — re-run seed_dev_sandbox.sql', ajersey;
    end if;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '1', tid, pid, jersey, 'RW',
      38.7, 1.3, 'C-6Y', 'Six-yard box · Center', 'goal',
      apid, 'cross', 'RB',
      25.3, 1.3, 'LHS-6Y', 'Six-yard box · Left half-space',
      1371, '2099-04-06T02:10:54.614Z'::timestamptz
    );

    -- 1 Bogwater #9 Missed Shot  (Olympus #15 → Bracken)
    tid := opp;
    jersey := '9';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '1', tid, pid, jersey, 'CF',
      39.2, 20.9, 'C-D', 'Zone 14', 'missed',
      apid, null, null,
      null, null, null, null,
      1448, '2099-04-06T02:12:15.921Z'::timestamptz
    );

    -- 1 Medville #10 Missed Shot  (Ari → Nova)
    tid := marauders;
    jersey := '10';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Medville jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '1', tid, pid, jersey, 'CF',
      18.7, 21.3, 'LHS-D', 'Left half-space · Top of the box', 'missed',
      apid, null, null,
      null, null, null, null,
      1646, '2099-04-06T02:15:42.825Z'::timestamptz
    );

    -- 1 Medville #9 Missed Shot  (Addison → Pip)
    tid := marauders;
    jersey := '9';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Medville jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '1', tid, pid, jersey, 'RW',
      49, 26.3, 'RHS-AT', 'Right half-space · Attacking third', 'missed',
      apid, null, null,
      null, null, null, null,
      2078, '2099-04-06T02:23:15.881Z'::timestamptz
    );

    -- 1 Bogwater #6 Shot Blocked  (Olympus #55 → Peat)
    tid := opp;
    jersey := '6';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '1', tid, pid, jersey, 'LCB',
      15.1, 33.9, 'LHS-AT', 'Left half-space · Attacking third', 'blocked',
      apid, null, null,
      null, null, null, null,
      2181, '2099-04-06T02:25:03.690Z'::timestamptz
    );

    -- 1 Bogwater #21 Shot Blocked  (Olympus #21 → Newt)
    tid := opp;
    jersey := '21';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '1', tid, pid, jersey, 'CF',
      40.6, 18.8, 'C-D', 'Zone 14', 'blocked',
      apid, null, null,
      null, null, null, null,
      2271, '2099-04-06T02:26:38.137Z'::timestamptz
    );

    -- 1 Bogwater #10 Missed Shot  (Olympus #10 → Reed)
    tid := opp;
    jersey := '10';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '1', tid, pid, jersey, 'DM',
      25.3, 3.8, 'LHS-6Y', 'Six-yard box · Left half-space', 'missed',
      apid, null, null,
      null, null, null, null,
      2280, '2099-04-06T02:26:47.954Z'::timestamptz
    );

    -- 2 Bogwater #8 Missed Shot  (Olympus #24 → Fen)
    tid := opp;
    jersey := '8';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '2', tid, pid, jersey, 'LM',
      40.2, 28.8, 'C-AT', 'Center · Attacking third', 'missed',
      apid, null, null,
      null, null, null, null,
      120, '2099-04-06T02:30:07.835Z'::timestamptz
    );

    -- 2 Bogwater #7 Missed Shot  (Olympus #37 → Marsh)
    tid := opp;
    jersey := '7';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '2', tid, pid, jersey, 'RW',
      41.8, 21.1, 'C-D', 'Zone 14', 'missed',
      apid, null, null,
      null, null, null, null,
      1017, '2099-04-06T02:53:22.795Z'::timestamptz
    );

    -- 2 Medville #14 Missed Shot  (Kailee → Pretzel)
    tid := marauders;
    jersey := '14';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Medville jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    ajersey := '10';
    select r.player_id into apid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = ajersey
    limit 1;
    if apid is null then
      raise exception 'Medville assist jersey % missing — re-run seed_dev_sandbox.sql', ajersey;
    end if;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '2', tid, pid, jersey, 'CF',
      43.1, 8.6, 'RHS-PS', 'Box · Right half-space', 'missed',
      apid, 'pass', 'CF',
      30.5, 14.5, 'C-BOX', 'Box · Center',
      1258, '2099-04-06T02:59:36.548Z'::timestamptz
    );

    -- 2 Medville #9 Shot on Goal  (Addison → Pip)
    tid := marauders;
    jersey := '9';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Medville jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '2', tid, pid, jersey, 'RW',
      29.9, 2.4, 'C-6Y', 'Six-yard box · Center', 'on-target',
      apid, null, null,
      null, null, null, null,
      1603, '2099-04-06T03:08:32.776Z'::timestamptz
    );

    -- 2 Medville #9 Shot on Goal  (Addison → Pip)
    tid := marauders;
    jersey := '9';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Medville jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '2', tid, pid, jersey, 'RW',
      30.4, 0.2, 'C-6Y', 'Six-yard box · Center', 'on-target',
      apid, null, null,
      null, null, null, null,
      1608, '2099-04-06T03:08:39.977Z'::timestamptz
    );

    -- 2 Bogwater #10 Shot on Goal  (Olympus #10 → Reed)
    tid := opp;
    jersey := '10';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '2', tid, pid, jersey, 'DM',
      25.9, 14, 'C-BOX', 'Box · Center', 'on-target',
      apid, null, null,
      null, null, null, null,
      1708, '2099-04-06T03:11:16.763Z'::timestamptz
    );

    -- 2 Bogwater #14 Missed Shot  (Olympus #14 → Moss)
    tid := opp;
    jersey := '14';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '2', tid, pid, jersey, 'RM',
      18.6, 8.9, 'LHS-PS', 'Box · Left half-space', 'missed',
      apid, null, null,
      null, null, null, null,
      1811, '2099-04-06T03:13:56.070Z'::timestamptz
    );

    -- 2 Medville #8 Missed Shot  (Sharky → Ziggy)
    tid := marauders;
    jersey := '8';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Medville jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '2', tid, pid, jersey, 'RM',
      30.7, 31.7, 'C-AT', 'Center · Attacking third', 'missed',
      apid, null, null,
      null, null, null, null,
      2238, '2099-04-06T03:24:59.520Z'::timestamptz
    );

    -- 2 Bogwater #7 Goal  (Olympus #37 → Marsh)
    tid := opp;
    jersey := '7';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '2', tid, pid, jersey, 'RW',
      43.4, 29.2, 'RHS-AT', 'Right half-space · Attacking third', 'goal',
      apid, null, null,
      null, null, null, null,
      2292, '2099-04-06T03:26:23.211Z'::timestamptz
    );

    -- 2 Medville #7 Missed Shot  (Savvy → Nimbus)
    tid := marauders;
    jersey := '7';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Medville jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, '2', tid, pid, jersey, 'DM',
      33.6, 29, 'C-AT', 'Center · Attacking third', 'missed',
      apid, null, null,
      null, null, null, null,
      2340, '2099-04-06T03:27:38.509Z'::timestamptz
    );

    -- ET1 Bogwater #14 Shot on Goal  (Olympus #14 → Moss)
    tid := opp;
    jersey := '14';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, 'ET1', tid, pid, jersey, 'RM',
      46.8, 12.9, 'RHS-BOX', 'Box · Right half-space', 'on-target',
      apid, null, null,
      null, null, null, null,
      60, '2099-04-06T03:39:27.906Z'::timestamptz
    );

    -- ET1 Medville #10 Shot Blocked  (Ari → Nova)
    tid := marauders;
    jersey := '10';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Medville jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, 'ET1', tid, pid, jersey, 'CF',
      35.8, 27.5, 'C-AT', 'Center · Attacking third', 'blocked',
      apid, null, null,
      null, null, null, null,
      173, '2099-04-06T03:41:41.935Z'::timestamptz
    );

    -- ET1 Bogwater #14 Missed Shot  (Olympus #14 → Moss)
    tid := opp;
    jersey := '14';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, 'ET1', tid, pid, jersey, 'RM',
      27, 12.9, 'C-BOX', 'Box · Center', 'missed',
      apid, null, null,
      null, null, null, null,
      181, '2099-04-06T03:41:50.752Z'::timestamptz
    );

    -- ET1 Bogwater #9 Missed Shot  (Olympus #15 → Bracken)
    tid := opp;
    jersey := '9';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    ajersey := '11';
    select r.player_id into apid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = ajersey
    limit 1;
    if apid is null then
      raise exception 'Bogwater assist jersey % missing — re-run seed_dev_sandbox.sql', ajersey;
    end if;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, 'ET1', tid, pid, jersey, 'CF',
      25, 5.4, 'LHS-6Y', 'Six-yard box · Left half-space', 'missed',
      apid, 'cross', 'LW',
      66.7, 1.2, 'RW-6Y', 'Right wide · Six-yard',
      295, '2099-04-06T03:44:06.451Z'::timestamptz
    );

    -- ET1 Medville #10 Shot Blocked  (Ari → Nova)
    tid := marauders;
    jersey := '10';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Medville jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, 'ET1', tid, pid, jersey, 'CF',
      34.8, 21, 'C-D', 'Zone 14', 'blocked',
      apid, null, null,
      null, null, null, null,
      326, '2099-04-06T03:44:43.254Z'::timestamptz
    );

    -- ET1 Bogwater #16 Missed Shot  (Olympus #97 → Duckweed)
    tid := opp;
    jersey := '16';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, 'ET1', tid, pid, jersey, 'DM',
      45.4, 18, 'RHS-D', 'Right half-space · Top of the box', 'missed',
      apid, null, null,
      null, null, null, null,
      417, '2099-04-06T03:46:30.796Z'::timestamptz
    );

    -- ET1 Medville #6 Shot on Goal  (Jackie → Cosmo)
    tid := marauders;
    jersey := '6';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Medville jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, 'ET1', tid, pid, jersey, 'LM',
      40.7, 30.7, 'C-AT', 'Center · Attacking third', 'on-target',
      apid, null, null,
      null, null, null, null,
      540, '2099-04-06T03:48:56.031Z'::timestamptz
    );

    -- ET2 Bogwater #9 Goal  (Olympus #15 → Bracken)
    tid := opp;
    jersey := '9';
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season
      and r.jersey_number = jersey
    limit 1;
    if pid is null then
      raise exception 'Bogwater jersey % missing — re-run seed_dev_sandbox.sql', jersey;
    end if;
    apid := null;
    ajersey := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time, position,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_position,
      assist_x, assist_y, assist_zone_id, assist_zone_label,
      game_clock_seconds, created_at
    ) values (
      gid, 'ET2', tid, pid, jersey, 'CF',
      45.9, 47.8, 'RHS-HALF', 'Right half-space · Toward halfway', 'goal',
      apid, null, null,
      null, null, null, null,
      300, '2099-04-06T03:54:28.983Z'::timestamptz
    );

  raise notice 'Imported 30 Olympus shots as Medville @ Bogwater (2099-04-05)';
end;
$$;
