#!/usr/bin/env python3
"""Replay a real recorded game onto DEV Sandbox (Medville vs Bogwater).

Reads recorded data/bengals-shots-vs-olympus-2026-08-19.csv (Brighton @ Olympus,
region, extra time) and writes supabase/seed_dev_recorded_game.sql.

Brighton jerseys are mapped onto the Medville cartoon roster by role; Olympus
jerseys onto Bogwater. Re-run this script after CSV or mapping edits, then:

  supabase db query --linked -f supabase/seed_dev_recorded_game.sql

DEV ONLY — never run the generated SQL on prod.
"""
from __future__ import annotations

import csv
import pathlib
from datetime import datetime

ROOT = pathlib.Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "recorded data" / "bengals-shots-vs-olympus-2026-08-19.csv"
OUT = ROOT / "supabase" / "seed_dev_recorded_game.sql"

GAME_DATE = "2099-04-05"
GAME_TYPE = "playoffs"
CREATED_DATE = "2099-04-06"  # UTC date of original timestamps (evening MT → next day)

RESULT = {
    "Goal": "goal",
    "Shot on Goal": "on-target",
    "Shot Blocked": "blocked",
    "Missed Shot": "missed",
}
ASSIST = {"Pass": "pass", "Gap": "gap", "Cross": "cross"}

# Brighton jersey → Medville jersey, pitch slot, note
US_MAP = {
    "5": ("5", "RB", "Kate → Biscuit"),
    "8": ("9", "RW", "Addison → Pip"),
    "9": ("11", "LW", "Georgia → Pixel"),
    "13": ("14", "CF", "Kailee → Pretzel"),
    "17": ("6", "LM", "Jackie → Cosmo"),
    "24": ("7", "DM", "Savvy → Nimbus"),
    "26": ("8", "RM", "Sharky → Ziggy"),
    "32": ("10", "CF", "Ari → Nova"),
}

# Olympus jersey → Bogwater jersey, pitch slot, note
OPP_MAP = {
    "10": ("10", "DM", "Olympus #10 → Reed"),
    "14": ("14", "RM", "Olympus #14 → Moss"),
    "15": ("9", "CF", "Olympus #15 → Bracken"),
    "21": ("21", "CF", "Olympus #21 → Newt"),
    "24": ("8", "LM", "Olympus #24 → Fen"),
    "29": ("11", "LW", "Olympus #29 → Toad"),
    "37": ("7", "RW", "Olympus #37 → Marsh"),
    "55": ("6", "LCB", "Olympus #55 → Peat"),
    "97": ("16", "DM", "Olympus #97 → Duckweed"),
}

# Elapsed-second span inside each period (HS 40:00, ET 10:00).
PERIOD_CLOCK = {
    "1": (180, 2280),
    "2": (120, 2340),
    "ET1": (60, 540),
    "ET2": (300, 480),
}


def esc(s):
    if s is None or s == "":
        return "null"
    return "'" + str(s).replace("'", "''") + "'"


def num_or_null(s):
    s = (s or "").strip()
    return "null" if s == "" else s


def read_csv(path: pathlib.Path):
    text = path.read_text(encoding="utf-8-sig")
    first = text.splitlines()[0]
    delim = "\t" if "\t" in first else ","
    rows = list(csv.DictReader(text.splitlines(), delimiter=delim))
    return [{(k or "").strip(): (v or "").strip() for k, v in r.items()} for r in rows]


def parse_time(s: str) -> datetime:
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


def remap_created_at(stamp: str) -> str:
    _date, rest = stamp.split("T", 1)
    return f"{CREATED_DATE}T{rest}"


def clock_seconds(rows: list[dict]) -> dict[int, int]:
    grouped: dict[str, list[dict]] = {}
    for r in rows:
        grouped.setdefault(r.get("half") or "1", []).append(r)
    out: dict[int, int] = {}
    for period, group in grouped.items():
        lo, hi = PERIOD_CLOCK[period]
        ordered = sorted(group, key=lambda r: r["time"])
        t0 = parse_time(ordered[0]["time"])
        t1 = parse_time(ordered[-1]["time"])
        span = (t1 - t0).total_seconds()
        for r in ordered:
            if span <= 0:
                out[id(r)] = lo
            else:
                frac = (parse_time(r["time"]) - t0).total_seconds() / span
                out[id(r)] = int(round(lo + frac * (hi - lo)))
    return out


def map_jersey(team: str, number: str) -> tuple[str, str, str]:
    table = US_MAP if team == "us" else OPP_MAP
    if number not in table:
        raise SystemExit(f"Unmapped {team} jersey #{number} — add it to the map")
    return table[number]


def mapping_comment_lines(title: str, table: dict) -> list[str]:
    lines = [f"-- {title}"]
    for src in sorted(table, key=lambda n: (len(n), n)):
        dest, pos, note = table[src]
        lines.append(f"--   #{src:>2} → #{dest:<3} {pos:<3}  {note}")
    return lines


def main():
    rows = read_csv(CSV_PATH)
    if not rows:
        raise SystemExit(f"No rows in {CSV_PATH}")
    clocks = clock_seconds(rows)
    chronological = list(reversed(rows))

    lines = [
        "-- DEV ONLY — replay a real recorded game onto Medville / Bogwater.",
        "-- Do NOT run on PROD.",
        "--",
        f"-- Source: {CSV_PATH.relative_to(ROOT)}",
        "-- Generated by scripts/generate_dev_recorded_game_sql.py — re-run after CSV or mapping edits.",
        f"-- Attaches to DEV Sandbox {GAME_TYPE} on {GAME_DATE} (Bogwater home, Medville away).",
        "-- Safe to re-run: replaces shots on that game only.",
        "--",
        *mapping_comment_lines("Brighton → Medville", US_MAP),
        "--",
        *mapping_comment_lines("Olympus → Bogwater", OPP_MAP),
        "",
        "do $$",
        "declare",
        "  marauders uuid;",
        "  season uuid;",
        "  opp uuid;",
        "  gid uuid;",
        "  tid uuid;",
        "  pid uuid;",
        "  apid uuid;",
        "  jersey text;",
        "  ajersey text;",
        "begin",
        "  select id into marauders from public.teams where is_brighton limit 1;",
        "  select id into season from public.seasons where label = 'DEV Sandbox' limit 1;",
        "  select id into opp from public.teams where name = 'Bogwater Badgers' limit 1;",
        "  if marauders is null or season is null or opp is null then",
        "    raise exception 'Run supabase/seed_dev_sandbox.sql on DEV first';",
        "  end if;",
        "",
        "  select g.id into gid from public.games g",
        "  where g.season_id = season and g.date = " + esc(GAME_DATE),
        "    and g.home_team_id = opp and g.away_team_id = marauders",
        "  limit 1;",
        "  if gid is null then",
        "    insert into public.games (",
        "      season_id, date, game_type, home_team_id, away_team_id, our_team_id,",
        "      clock_direction, clock_half_length_sec, clock_et_length_sec",
        "    ) values (",
        f"      season, {esc(GAME_DATE)}, {esc(GAME_TYPE)}, opp, marauders, marauders,",
        "      'down', 2400, 600",
        "    ) returning id into gid;",
        "  else",
        "    update public.games",
        "    set clock_direction = 'down',",
        "        clock_half_length_sec = 2400,",
        "        clock_et_length_sec = 600",
        "    where id = gid;",
        "  end if;",
        "",
        "  delete from public.shots where game_id = gid;",
        "",
        f"  -- {len(rows)} shots, oldest first",
    ]

    for r in chronological:
        result = RESULT.get(r.get("result", ""))
        if not result:
            raise SystemExit(f"Unknown result {r.get('result')!r}")
        period = r.get("half") or "1"
        if period not in ("1", "2", "ET1", "ET2"):
            raise SystemExit(f"bad period {period}")
        is_us = r.get("team") == "us"
        src_jersey = r.get("player_number") or ""
        src_assist = r.get("assisted_by_number") or ""
        assist_type = ASSIST.get(r.get("assist_type", "")) if r.get("assist_type") else None
        clock = clocks[id(r)]
        created = remap_created_at(r["time"])

        dest_jersey = dest_pos = note = None
        if src_jersey:
            dest_jersey, dest_pos, note = map_jersey("us" if is_us else "opponent", src_jersey)

        assist_jersey = assist_pos = None
        if src_assist and assist_type:
            assist_jersey, assist_pos, _assist_note = map_jersey(
                "us" if is_us else "opponent", src_assist
            )

        who = "Medville" if is_us else "Bogwater"
        comment = f"    -- {period} {who} #{dest_jersey or '?'} {r.get('result')}"
        if note:
            comment += f"  ({note})"
        lines.append("")
        lines.append(comment)
        lines.append(f"    tid := {'marauders' if is_us else 'opp'};")
        if dest_jersey:
            lines.append(f"    jersey := {esc(dest_jersey)};")
            lines.append("    select r.player_id into pid from public.rosters r")
            lines.append("    where r.team_id = tid and r.season_id = season")
            lines.append("      and r.jersey_number = jersey")
            lines.append("    limit 1;")
            lines.append("    if pid is null then")
            lines.append(
                f"      raise exception '{who} jersey % missing — re-run seed_dev_sandbox.sql', jersey;"
            )
            lines.append("    end if;")
        else:
            lines.append("    pid := null;")
            lines.append("    jersey := null;")

        if assist_jersey:
            lines.append(f"    ajersey := {esc(assist_jersey)};")
            lines.append("    select r.player_id into apid from public.rosters r")
            lines.append("    where r.team_id = tid and r.season_id = season")
            lines.append("      and r.jersey_number = ajersey")
            lines.append("    limit 1;")
            lines.append("    if apid is null then")
            lines.append(
                f"      raise exception '{who} assist jersey % missing — re-run seed_dev_sandbox.sql', ajersey;"
            )
            lines.append("    end if;")
        else:
            lines.append("    apid := null;")
            lines.append("    ajersey := null;")

        pos = esc(dest_pos) if dest_pos else "null"
        apos = esc(assist_pos) if assist_jersey else "null"
        atype = esc(assist_type) if assist_type else "null"
        ax = num_or_null(r.get("assist_x")) if assist_jersey else "null"
        ay = num_or_null(r.get("assist_y")) if assist_jersey else "null"
        azid = esc(r.get("assist_zone_id")) if assist_jersey and r.get("assist_zone_id") else "null"
        azlab = esc(r.get("assist_zone")) if assist_jersey and r.get("assist_zone") else "null"

        lines.append("    insert into public.shots (")
        lines.append("      game_id, period, team_id, player_id, jersey_number_at_time, position,")
        lines.append("      x, y, zone_id, zone_label, result,")
        lines.append("      assist_player_id, assist_type, assist_position,")
        lines.append("      assist_x, assist_y, assist_zone_id, assist_zone_label,")
        lines.append("      game_clock_seconds, created_at")
        lines.append("    ) values (")
        lines.append(f"      gid, {esc(period)}, tid, pid, jersey, {pos},")
        lines.append(
            f"      {num_or_null(r.get('shot_x'))}, {num_or_null(r.get('shot_y'))}, "
            f"{esc(r.get('shot_zone_id'))}, {esc(r.get('shot_zone'))}, {esc(result)},"
        )
        lines.append(f"      apid, {atype}, {apos},")
        lines.append(f"      {ax}, {ay}, {azid}, {azlab},")
        lines.append(f"      {clock}, {esc(created)}::timestamptz")
        lines.append("    );")

    lines += [
        "",
        f"  raise notice 'Imported {len(rows)} Olympus shots as Medville @ Bogwater ({GAME_DATE})';",
        "end;",
        "$$;",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(rows)} shots, {OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
